import { usePlane, useTrimesh } from '@react-three/cannon';

export default function Hall({nodes, materials}) {

  return (
   <>
    <group dispose={null} name='Hall'>
      <group
        name="Hall-Spots01"
        position={[90.746, 0.651, 40.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots03"
        position={[57.49, 0.651, 40.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder004"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder004?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder004_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder004_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots05"
        position={[26.798, 0.651, 40.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder005"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder005?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder005_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder005_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots07"
        position={[1.303, 0.651, 40.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder006"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder006?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder006_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder006_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots02"
        position={[90.746, 0.651, 94.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder008"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder008?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder008_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder008_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots04"
        position={[57.49, 0.651, 94.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder013"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder013?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder013_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder013_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots06"
        position={[26.798, 0.651, 94.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder015"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder015?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder015_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder015_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Spots08"
        position={[1.303, 0.651, 94.567]}
        scale={1.981}
      >
        <mesh
          name="Cylinder016"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder016?.geometry}
          material={materials["screen-white"]}
        />
        <mesh
          name="Cylinder016_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cylinder016_1?.geometry}
          material={materials["neon-2"]}
        />
      </group>
      <group
        name="Hall-Painting02"
        position={[31.066, 8.83, 102.43]}
        rotation={[Math.PI, -0.004, Math.PI]}
      >
        <mesh
          name="Cube010"
          castShadow
          receiveShadow
          geometry={nodes?.Cube010?.geometry}
          material={materials.Painting02}
        />
        <mesh
          name="Cube010_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cube010_1?.geometry}
          material={materials.screen}
        />
      </group>
      <group
        name="Hall-Painting01"
        position={[57.477, 8.83, 102.43]}
        rotation={[Math.PI, -0.004, Math.PI]}
      >
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes?.Cube007?.geometry}
          material={materials.Painting01}
        />
        <mesh
          name="Cube007_1"
          castShadow
          receiveShadow
          geometry={nodes?.Cube007_1?.geometry}
          material={materials.screen}
        />
      </group>
      <group name="Hall-Door" position={[-3.662, 56.197, 74.989]}>
        <mesh
          name="Hall-Door-Border"
          castShadow
          receiveShadow
          geometry={nodes["Hall-Door-Border"]?.geometry}
          material={materials["Material.004"]}
          position={[0, -1, -0.66]}
        >
          <mesh
            name="CTRL_Hole"
            castShadow
            receiveShadow
            geometry={nodes?.CTRL_Hole?.geometry}
            material={materials.hidden_material}
          />
        </mesh>
        <group name="Hall-Door-Frame" position={[0, -1, -0.66]}>
          <mesh
            name="Plane193"
            castShadow
            receiveShadow
            geometry={nodes?.Plane193?.geometry}
            material={materials.grey}
          />
          <mesh
            name="Plane193_1"
            castShadow
            receiveShadow
            geometry={nodes?.Plane193_1?.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Plane193_2"
            castShadow
            receiveShadow
            geometry={nodes?.Plane193_2?.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Handle"
            castShadow
            receiveShadow
            geometry={nodes?.Handle?.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Lock"
            castShadow
            receiveShadow
            geometry={nodes?.Lock?.geometry}
            material={materials["Material.001"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
  </group>
   </>
  )
}